services:
  nginx:
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot

    ports:
      - "80:80"
      - "443:443"
