# .github/workflows/docker-publish.yml
name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set short SHA
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build ais_relay_app
      run: docker build -t ghcr.io/sunet/ais_relay_app:${SHORT_SHA} ./app

    - name: Build ais_relay_stunnel
      run: docker build -t ghcr.io/sunet/ais_relay_stunnel:${SHORT_SHA} ./stunnel

    - name: Push images
      run: |
        docker push ghcr.io/sunet/ais_relay_app:${SHORT_SHA}
        docker push ghcr.io/sunet/ais_relay_stunnel:${SHORT_SHA}
